services:
  - name: kenya-constitution-ai
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GROQ_API_KEY
        sync: false
